version: '3'
services:
    nginx_load_balancer:
        image: nginx
        volumes:
            - './nginx/default.conf:/etc/nginx/nginx.conf'
        ports:
            - '8080:80'
    app1:
        container_name: app1
        image: node-app
        environment:
            - APPID=8081
    app2:
        container_name: app2
        image: node-app
        environment:
            - APPID=8082
    app3:
        container_name: app3
        image: node-app
        environment:
            - APPID=8083
    app4:
        container_name: app4
        image: node-app
        environment:
            - APPID=8084